config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'
  resources :todo_lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  def index
    @todo_lists = TodoList.all
  end

  def show
  end

  def new
    @todo_list = TodoList.new
  end

  def edit
  end

  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Todo list', welcome_index_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= todo_lists_path %>">Show</a></li>
        <li><a href="<%= new_todo_list_path %>">Add</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <%= yield %>
  </body>
</html>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true, html: { class: "container center forms" }) do |form| %>
    <% if todo_list.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

          <ul>
            <% todo_list.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field form-group">
      <%= form.label :title %>
      <%= form.text_field :title, id: :todo_list_title, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :description %>
      <%= form.text_area :description, id: :todo_list_description, class: "form-control" %>
    </div>

    <div class="actions form-group">
      <%= form.submit 'Add', class: "btn btn-primary" %>
    </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="headings">Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<div class="">
  <table class="table-hover paleBlueRows" align="center">
    <thead>
    <tr class="">
      <th class="column-title">Title</th>
      <th class="column-desc">Description</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @todo_lists.each do |todo_list| %>
        <tr>
          <td><%= todo_list.title %></td>
          <td><%= todo_list.description %></td>
          <td><%= link_to 'Show', todo_list, class: "btn btn-primary" %></td>
          <td><%= link_to 'Edit', edit_todo_list_path(todo_list), class: "btn btn-primary" %></td>
          <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/todo_lists/new.html.erb
<h1 class="headings">New Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

app/views/todo_lists/show.html.erb
<div class="container center forms">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @todo_list.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @todo_list.description %>
  </p>

  <%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
  <%= link_to 'Back', todo_lists_path %>
</div>

app/views/welcome/index.html.erb
<h1 class="container headings">Welcome to TODO app</h1>